// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOEJ6F0Sw9YVOwOJdsk_Hu6yPZCSbNoY',
    appId: '1:156687276225:web:b518b176e9fcfbdef5dc40',
    messagingSenderId: '156687276225',
    projectId: 'product-db-54d05',
    authDomain: 'product-db-54d05.firebaseapp.com',
    databaseURL: 'https://product-db-54d05-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-54d05.appspot.com',
    measurementId: 'G-XJTW8BKC0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xsv0iAw5dHgk4AWa24pYtBH9jbG55K8',
    appId: '1:156687276225:android:ea1eff593a6b2afdf5dc40',
    messagingSenderId: '156687276225',
    projectId: 'product-db-54d05',
    databaseURL: 'https://product-db-54d05-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-54d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBtV4cmOf-BRsoTIOC0aq4EXvlUNJtaY',
    appId: '1:156687276225:ios:a1f3f8ec21baccb9f5dc40',
    messagingSenderId: '156687276225',
    projectId: 'product-db-54d05',
    databaseURL: 'https://product-db-54d05-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-54d05.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBtV4cmOf-BRsoTIOC0aq4EXvlUNJtaY',
    appId: '1:156687276225:ios:a1f3f8ec21baccb9f5dc40',
    messagingSenderId: '156687276225',
    projectId: 'product-db-54d05',
    databaseURL: 'https://product-db-54d05-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-54d05.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEOEJ6F0Sw9YVOwOJdsk_Hu6yPZCSbNoY',
    appId: '1:156687276225:web:c9748803e6d96a4df5dc40',
    messagingSenderId: '156687276225',
    projectId: 'product-db-54d05',
    authDomain: 'product-db-54d05.firebaseapp.com',
    databaseURL: 'https://product-db-54d05-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-54d05.appspot.com',
    measurementId: 'G-ZND18V1D0B',
  );
}
